### ISSUE TITLE
I can't get date with exact time

### ISSUE THREAD

**Issue by jangot** [antonmedv/year#1]
I use the package but then tried to get date with exact time and I got error:
`const day = require('@year/2018/01/01/23/05');`

```Error: Cannot find module '@year/2018/01/01/23/05'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/..../year/index.js:1:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)```

**Comment by antonmedv** [comment]
Only Date's supported:
```js
const day = require('@year/2018/01/01');
```

https://github.com/antonmedv/year/blob/master/packages/1970/01/01/index.js

For time, we need to create @time/* packages 👐

**Comment by jangot** [comment]
This package has name `year` by this logics I need make `require("@year/2012")` but I can use exact day.

**Comment by antonmedv** [comment]
Examples of packages: `lodash/map` `antd/lib/button` `@year/2018/01/01`
So everything is ok, it's by design. Read docs.
